#HOKUSAI
FDPS_HOME = ../../../src/
NVCC = time nvcc
INC = -I$(FDPS_HOME)
CXXFLAGS = -O3
CXXFLAGS += -DPARTICLE_SIMULATOR_THREAD_PARALLEL
CXXFLAGS += -DENABLE_GPU
COMP = --compiler-bindir=g++ --compiler-options=-fopenmp

PROGRAM = sph.out
CPPOBJS = main.cpp
CUOBJS  = $(patsubst %.cu, %.o, $(wildcard *.cu))
CPPHDRS = $(wildcard *.h)

all:	$(CPPOBJS) $(CUOBJS) $(CPPHDRS)
	@echo "Linking object files..."
	$(NVCC) $(CXXFLAGS) $(INC) $(CPPOBJS) $(CUOBJS) -o $(PROGRAM) -lgomp
	@echo "Link Success! [$(PROGRAM)]"

%.o:	%.cpp $(CPPHDRS)
	@echo "Building $< ..."
	$(NVCC) $(INC) -c $< $(CXXFLAGS) $(COMP) -lgomp
	@echo "[CPP $< OK]"
	@echo ""

%.o:	%.cu $(CPPHDRS)
	@echo "Building $< ..."
	@$(NVCC) $(INC) -c $< $(CXXFLAGS) -o $@
	@echo "[CUDA $< OK]"
	@echo ""

clean:
	rm *.o *.out

