# (i) compiler, compile options
CXX = g++-mp-8
CXXFLAGS = -Wall -O0
LDFLAGS =

TARGET = a.out

all: main.o
	$(CXX) $(CXXFLAGS) -o $(TARGET) $< $(LDFLAGS)

main.o: main.cpp
	$(CXX) -c $< $(CXXFLAGS)

clean:
	rm -f main.o

distclean: clean
	rm -f $(TARGET)
