# (i) Compiler and compile options
CC = icpc
CFLAGS = -std=c++11 -O3 -ipo -xCORE-AVX512 -no-prec-div
CFLASG += -qno-opt-dynamic-align
CFLAGS += -fimf-use-svml
CFLAGS += -fp-model consistent
CFLAGS += -I./

# (ii) Job submission variables
QSUB = pjsub
JOB_FILE_NAME = job.hokusai-bw.sh
WORKDIR = ./work-hokusai-bw

# (iii) Executable
CPPOBJS = $(patsubst %.cpp, %.o, $(wildcard *.cpp))
CPPHDRS = $(wildcard *.h)
PROGRAM = a.out

.PHONY:	clean all

all: $(CPPOBJS) $(CPPHDRS)
	$(CC) $(CFLAGS) $(CPPOBJS) -o $(PROGRAM)
	mkdir -p $(WORKDIR)
	mv $(PROGRAM) $(WORKDIR)
	cp $(JOB_FILE_NAME) $(WORKDIR)
	cd $(WORKDIR); $(QSUB) $(JOB_FILE_NAME) 

%.o: %.cpp $(CPPHDRS)
	$(CC) -c $< $(CFLAGS)

clean:
	rm $(PROGRAM) *.o
