CC = g++-mp-8
CFLAGS = -std=c++11 -O3 -ffast-math -funroll-loops 

CPPOBJS = $(patsubst %.cpp, %.o, $(wildcard *.cpp))
CPPHDRS = $(wildcard *.h)
PROGRAM = a.out

.PHONY:	clean all

all: $(CPPOBJS) $(CPPHDRS)
	$(CC) $(CFLAGS) $(WARNINGS) $(CPPOBJS) -o $(PROGRAM) $(LIBS) $(PS_PATH)

%.o: %.cpp $(CPPHDRS)
	$(CC) -c $< $(CFLAGS) $(WARNINGS) $(PS_PATH)

clean:
	rm $(PROGRAM) *.o
