# (i) DISLIN setting
DISLIN_ROOT = /home/namekata/dislin
INC = -I$(DISLIN_ROOT)
LIBS = $(DISLIN_ROOT)/libdiscpp.so -lm

# (ii) Compiler, compile options, etc.
CXX=time -p icpc
#CXX=time -p mpiicpc
#CXXFLAGS = -std=c++11 -O0 -ftrapuv -debug all -g
CXXFLAGS = -std=c++11 -O3 -ipo -xCORE-AVX512 -no-prec-div
#### [Important] ####
#  The following options may be needed to keep
#  the reproducibility of the run.
#  Adding the options may cause a drop in performance,
#  but is useful when debugging the code.
#  (for details, see ./doc/Under_What_Conditions*.pdf)
CXXFLASG += -qno-opt-dynamic-align
CXXFLAGS += -fimf-use-svml 
CXXFLAGS += -fp-model consistent
#####################

# (ii) Object files, etc.
CPPOBJS = $(patsubst %.cpp, %.o, $(wildcard *.cpp))
CPPHDRS = $(wildcard *.h) $(wildcard *.hpp)
PROGRAM = a.out

.PHONY:	clean all

all: $(CPPOBJS) $(CPPHDRS)
	$(CXX) $(CXXFLAGS) $(CPPOBJS) -o $(PROGRAM) $(INC) $(LIBS) 

%.o: %.cpp $(CPPHDRS)
	$(CXX) -c $< $(CXXFLAGS) $(INC)

clean:
	rm -f $(CPPOBJS)

distclean: clean
	rm -f $(PROGRAM)
	rm *.tbl *.met

