#pragma once 
void UpdateCosmologicalParameters(void);
void UpdateAdaptiveSofteningFactor(void);
double CalcCriticalDensityZ0(void);
double CalcHubbleParameterZ0(void);
double CalcCriticalDensityZ(void);
double CalcHubbleParameterZ(void);
double CalcOverDensityZ(void);
double CalcVirializedDensityZ(void);
void CalcUniformSphereForce(void);
