/* Unit.c */
double GetMeanMolecularWeight(double MetallicityWeight);
double GetUnitGravitationalConstant(void);
double GetUnitAu(void);
double GetUnitKpc(void);
double GetUnitMpc(void);
double GetUnitVel(void);
double GetUnitLightVel(void);
double GetUnitHubble(void);
double GetUnitEnergy(void);
double GetUnitSpecificEnergy(void);
double GetUnitCoolingRate(void);
double GetUnitEnergyPerUnitTime(void);
double GetUnitInnerEnergy(void);
double GetUnitConversionFactorTemperatureToInnerEnergy(void);
double GetUnitConversionFactorInnerEnergyToTemperature(void);
double GetUnitDensity(void);
double GetUnitDensityCGS(void);
double GetUnitNumberDensityCGS(void);
double GetUnitMassSolarMass(void);
