# sample configure script
MPICXX=mpicxx
CXX=mpicxx
CXXFLAGS+=' -DORDERED_RECV'
CXXFLAGS+=' -DOVERLAP -DOVERLAP_PAIRLIST_THREAD'
CXXFLAGS+=' -DMT_LONG=4'
CXXFLAGS+=' -DTUNE_CBMAP'
CXXFLAGS+=' -DFMM_CARTESIAN'
CXXFLAGS+=' -DK_SIMD'
CXXFLAGS+=' -DNDEBUG'
CXXFLAGS+=' -DUSE_SHAKE -DSHARE_LIST'
CXXFLAGS+=' -DTIMER_DETAIL'
CXXFLAGS+=' -DUSE_PAIRLIST -DINDEX_PAIRLIST'
CXXFLAGS+=' -DMPIPARALLEL_OPENMP'
CXXFLAGS+=' -DMAX_PAIR=12000'
CXXFLAGS+=' -DPRE_CALC_SF'
CXXFLAGS+=' -DPBOUND=1'
CXXFLAGS+=' -DCALCQ_OPENMP'
CXXFLAGS+=' -DREDUCE_COS'
#CXXFLAGS+=' -DZERODIPOLE0'
CXXFLAGS+=' -DSIMPLE_CUTOFF'
CXXFLAGS+=' -DSIMPLE_LJ'
#CXXFLAGS+=' -DCHECK_ENERGY'
#CXXFLAGS+=' -DBINARY_DUMP'
#CXXFLAGS+=' -DBINARY_RESTORE'
#CXXFLAGS+=' -DCORRECT_LEAPFROG_RESTART'
##FFTW2DIR=  path of FFTW2
#CXXFLAGS+=" -I${FFTW2DIR}/include"
#LDFLAGS+=" -L${FFTW2DIR}/lib"
#LIBS+=' -lrfftw_mpi -lfftw_mpi -lrfftw -lfftw'
##HDF5DIR= path of HDF5
#CXXFLAGS+=" -I${HDF5DIR}/include"
#LDFLAGS+=" -L${HDF5DIR}/lib"
../cppmd${VERSION}/configure \
--host=sparc64-unknown-linux-gnu --build=x86_64-unknown-linux-gnu \
--with-hdf=no \
--enable-mr3exafmm  \
MPICXX="${MPICXX}" CXX="${CXX}" CXXFLAGS="${CXXFLAGS}" \
LDFLAGS="${LDFLAGS}" LIBS="${LIBS}" 

