#====================================================================
#  Makefile for unit tests
#    (included by ../Makefile)
#====================================================================

#--- PS::Vector3<T> extension
GTEST_SRCS += $(REL)/gtest_vec_ext.cpp

#--- COMM_TOOL::
GTEST_SRCS += $(REL)/gtest_comm_tool_SerDes.cpp
GTEST_SRCS += $(REL)/gtest_comm_tool_broadcast.cpp
GTEST_SRCS += $(REL)/gtest_comm_tool_allGather.cpp

#--- MD_EXT::boltzmann_dist
GTEST_SRCS += $(REL)/gtest_blz_dist.cpp

#--- MD_EXT::CellIndex
GTEST_SRCS += $(REL)/gtest_cell_index.cpp

#--- static array for FullParticle
GTEST_SRCS += $(REL)/gtest_fixed_vector.cpp
GTEST_SRCS += $(REL)/gtest_basic_connect.cpp

#--- IntraPair::
GTEST_SRCS += $(REL)/gtest_intra_pair.cpp

#--- force test
GTEST_SRCS += $(REL)/gtest_force_LJ.cpp
GTEST_SRCS += $(REL)/gtest_force_coulomb.cpp
GTEST_SRCS += $(REL)/gtest_force_bond.cpp
GTEST_SRCS += $(REL)/gtest_force_angle.cpp
GTEST_SRCS += $(REL)/gtest_force_dihedral.cpp
GTEST_SRCS += $(REL)/gtest_force_improper.cpp

#--- file I/O test
GTEST_SRCS += $(REL)/gtest_fileIO.cpp
