#-----------------------------------------------------------------------
#   Configuration of compile
#-----------------------------------------------------------------------
# (ii) Variables to specify compilers and compile options
# Serial or OpenMP cases
CC=gcc-mp-8
#CFLAGS   = -Wall -Wextra -ftrapv -fexceptions -g3 $(FDPS_INC)
CFLAGS = -O3 -ffast-math -funroll-loops $(FDPS_INC)
LDFLAGS =

#-----------------------------------------------------------------------
#   Source files
#-----------------------------------------------------------------------
%.o : %.c
	$(CC) $(CFLAGS) -c $<

TARGET = nbody.out

$(TARGET): main.o
	$(CC) $^ $(CFLAGS) -o $(TARGET) $(LDFLAGS)

clean:
	rm -f *.o *.s $(TARGET) *.dat

distclean: clean

